const textData = {
  common: {
    loading: "Loading...",
    saving: "Saving...",
    saveChanges: "Save Changes",
    delete: "Delete",
    edit: "Edit",
    cancel: "Cancel",
    search: "Search...",
    noData: "No data found.",
    logout: "Logout",
    status: "Status",
    actions: "Actions",
    sku: "SKU",
    category: "Category",
    quantity: "Qty",
    price: "Price",
    productName: "Product Name",
    date: "Date",
    time: "Time",
    weekly: "Weekly",
    backToLogin: "Back to Login",
  },
  login: {
    title: "Inventory Management System Login",
    subtitle: "Sign in to access your dashboard",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    forgotPassword: "Forgot Password?",
    loginButton: "Login",
    noAccount: "Don't have an account?",
    registerLink: "Register",
    emailPlaceholder: "admin@example.com",
    passwordPlaceholder: "••••••••",
  },
  forgotPassword: {
    title: "Forgot Password",
    subtitle: "Enter your email address to receive a secure password reset link.",
    emailLabel: "Email Address",
    submitButton: "Send Reset Link",
    successMessage: "If an account exists with that email, a reset link has been sent.",
    placeholderEmail: "name@example.com",
  },
  register: {
    title: "Inventory Management System Registration",
    subtitle: "Register to create a new account",
    step1: "Step 1 — Role Selection",
    commonDetails: "Common Details",
    roleFields: "Role Specific Fields",
    fullNameLabel: "Full Name",
    emailLabel: "Email Address",
    passwordLabel: "Password",
    confirmPasswordLabel: "Confirm Password",
    shopNameLabel: "Orgnization Name",
    mobileNumberLabel: "Mobile Number",
    genderLabel: "Gender",
    dobLabel: "Date of Birth",
    addressLabel: "Address",
    cityLabel: "City",
    stateLabel: "State",
    pincodeLabel: "Pincode",
    profilePhotoLabel: "Profile Photo (Optional)",
    roleLabel: "Select Role",
    registerButton: "Register",
    hasAccount: "Already have an account?",
    loginLink: "Login",
    placeholders: {
      fullName: "John Doe",
      email: "john@example.com",
      shopName: "e.g. Ahmedabad Mobile Store",
      mobile: "+1234567890",
      address: "123 Main St",
      city: "City",
      state: "State",
      pincode: "ZIP Code",
      education: "Degree / Certification",
      experience: "e.g. 5",
    },
    roles: {
      admin: "Admin",
      manager: "Inventory Manager",
      staff: "Inventory Staff",
    },
    adminFields: {
      id: "Admin ID (Auto Generated)",
      joiningDate: "Joining Date",
      education: "Education",
    },
    managerFields: {
      id: "Manager ID (Auto Generated)",
      joiningDate: "Joining Date",
      education: "Education",
      department: "Department",
      experience: "Years of Experience",
    },
    staffFields: {
      id: "Staff ID (Auto Generated)",
      joiningDate: "Joining Date",
      shiftTime: "Shift Time",
    },
  },
  resetPassword: {
    title: "Reset Password",
    subtitle: "Your new password must be different from previously used passwords.",
    newPasswordLabel: "New Password",
    confirmPasswordLabel: "Confirm New Password",
    submitButton: "Update Password",
    successMessage: "Your password has been reset successfully. Redirecting to login...",
    placeholderPassword: "••••••••",
  },
  managerDashboard: {
    sidebarTitle: "Manager Dashboard",
    navTitle: "Inventory Manager Dashboard",
    summary: {
      totalProducts: "Total Products",
      outOfStock: "Out of Stock",
      pendingApproval: "Pending Approval",
      inventoryValue: "Inventory Value",
      lowStock: "Low Stock",
    },
    analytics: {
      lowStockAlert: "Low Stock Alert (< 5)",
      topSelling: "Top Selling Products",
      categoryDist: "Category Distribution",
      salesTrend: "Sales Analytics (Revenue)",
      profitAnalysis: "Profit Analysis",
      movementPerf: "Movement Performance",
      supplierContrib: "Supplier Contribution",
      stockTrends: "Stock Added vs Removed",
    },
    profit: {
      purchaseValue: "Purchase Value",
      sellingValue: "Selling Value",
      actualProfit: "Actual Profit",
      potentialProfitNote: "Potential profit from current active inventory values.",
    },
    activity: {
      title: "Recent Activity Feed",
      searchPlaceholder: "Search product...",
      filterAll: "All Movements",
      filterSales: "Sales",
      filterRestocks: "Restocks",
      filterDamage: "Damage",
      filterDeletions: "Deletions",
      noMovements: "No movements match your search criteria.",
    },
    tabs: {
      dashboard: "Dashboard",
      approvals: "Approve Products",
      products: "Product Management",
      categories: "Categories & Suppliers",
      orders: "Purchase Orders",
      logs: "Log Analysis",
    },
    optimizationNote: "This module is currently being optimized for high-performance analytics.",
    noProducts: "No products found.",
  },
  adminDashboard: {
    sidebarTitle: "Admin Central",
    navTitle: "System Administration",
    adminUser: "System Admin",
    systemAdmin: "Full Access",
    searchPlaceholder: "Search system...",
    phase3Note: "Advanced Analytics Module",
    phase3Desc: "This section is under development in Phase 3 of the infrastructure upgrade.",
    tabs: {
      dashboard: "Overview",
      products: "Inventory",
      category: "Categories",
      attributes: "Attributes",
      orders: "Orders",
      users: "Users",
      onlineStore: "Storefront",
      reports: "Audit Logs",
      settings: "Settings",
      faq: "Support",
    },
    statCards: {
      earnings: "Total Value",
      orders: "Total Products",
      customers: "Categories",
      balance: "Low Stock",
    },
    recentAudit: "Recent System Activity",
    criticalAlerts: "Critical Stock Alerts",
  },
  adminAuditLogs: {
    title: "System Audit Logs",
    subtitle: "Track comprehensive movement and inventory adjustments.",
    loading: "Loading audit trail...",
    empty: "No activity logged yet.",
    table: {
      dateTime: "Date & Time",
      action: "Action/Reason",
      product: "Product Detail",
      qty: "Qty",
      location: "Location Flow",
      performedBy: "Performed By",
    },
  },
  adminAlerts: {
    title: "Inventory Action Required",
    subtitle: "Products currently at or below their defined minimum stock threshold.",
    warningsLabel: "Warnings",
    loading: "Analyzing inventory levels...",
    empty: {
      title: "Stock Levels Healthy!",
      message: "No active products are below their minimum threshold.",
    },
    table: {
      sku: "SKU",
      category: "Category",
      supplier: "Supplier",
      currentStock: "Current Stock",
      reqMin: "Req Min",
    },
  },
  categorySupplier: {
    manageTitle: "Manage Categories",
    tabs: {
      categories: "Categories",
      suppliers: "Suppliers",
    },
    form: {
      addCategory: "Add New Global Category",
      addSupplier: "Add New Supplier",
      categorySubtitle: "These categories are shared across all shops",
      name: "Category Name",
      description: "Description",
      supplierName: "Supplier Name",
      email: "Email",
      phone: "Phone",
      placeholders: {
        categoryName: "e.g. Electronics",
        supplierName: "e.g. Acme Corp",
        description: "Add a category description here...",
        email: "john@acme.com",
        phone: "555-0199",
      },
      buttons: {
        create: "Create Category",
        createSupplier: "Create Supplier",
      },
    },
    table: {
      name: "Name",
      description: "Description",
      contactInfo: "Contact Info",
      actions: "Actions",
      noCategories: "No categories found",
      noSuppliers: "No suppliers found",
    },
    success: {
      categoryCreated: "Category created successfully",
      supplierCreated: "Supplier created successfully",
    },
    errors: {
      load: "Failed to load data",
      deleteConfirm: "Are you sure you want to delete this item?",
      deleteFail: "Failed to delete item. It may be in use.",
    },
  },
  managerApprovals: {
    title: "Pending Product Approvals",
    subtitle: "Review products added by Staff before they enter active inventory.",
    pendingLabel: "Pending",
    table: {
      img: "Img",
      sku: "SKU",
      name: "Product Name",
      category: "Category",
      brand: "Brand",
      buyPrice: "Buy Price",
      sellPrice: "Sell Price",
      qty: "Qty",
      addedBy: "Added By",
      dateAdded: "Date Added",
      actions: "Actions",
    },
    loading: "Loading pending inventory...",
    empty: {
      title: "All Clear!",
      message: "No products are waiting for approval right now.",
    },
    tooltips: {
      approve: "Approve Product",
      reject: "Reject Product",
    },
  },
  purchaseOrder: {
    title: "Purchase Orders",
    subtitle: "Create and manage purchase orders",
    newOrder: "Create New Purchase Order",
    viewOrders: "View Orders",
    form: {
      selectSupplier: "Supplier Name",
      chooseSupplier: "Select a supplier...",
      selectProduct: "Product Name",
      chooseProduct: "Select a product...",
      orderItems: "Order Details",
      productName: "Product Name",
      qty: "Quantity",
      price: "Price per unit",
      total: "Total Amount",
      createButton: "Create Order",
      resetButton: "Reset",
      successAlert: "Order created successfully",
    },
    table: {
      orderId: "Order ID",
      supplier: "Supplier",
      product: "Product",
      qty: "Quantity",
      price: "Price",
      total: "Total",
      status: "Status",
      date: "Date",
    },
    status: {
      created: "Created",
    },
    empty: {
      title: "No purchase orders found",
      message: "Start by creating your first procurement order.",
      button: "Create First Order",
    },
    search: "Search by supplier or product...",
  },
  staffDashboard: {
    sidebarTitle: "InventoryNode",
    navTitle: "Inventory Staff Module",
    subtitle: "Manage your inventory tracking and product registration.",
    tabs: {
      profile: "Profile",
      dashboard: "Dashboard",
      addProduct: "Add Product",
      productList: "Product List",
      updateQuantity: "Update Quantity",
      productMovement: "Product Movement",
      lowStockAlerts: "Low Stock Alerts",
      barcodeScanner: "Barcode Scanner",
    },
    workflow: {
      title: "Product Status Workflow",
      subtitle: "Understand the lifecycle of new products added to the inventory.",
      step1: "Staff adds product",
      step2: "Status = Pending",
      step3: "Manager Reviews",
      step4: "Product Active",
    },
    updateQuantity: {
      title: "Update Product Quantity",
      selectCategory: "Select Category",
      selectProduct: "Select Product Name",
      quantityLabel: "Quantity (+ added / - removed)",
      dateLabel: "Date of Update",
      button: "Update Quantity",
      noProducts: "No products found in this category.",
      chooseCategory: "-- Choose Category --",
      chooseProduct: "-- Choose Product --",
    },
    lowStock: {
      title: "Low Stock Notifications",
      desc: "Inform staff to notify manager and prevent stock shortage.",
      allStocked: "✅ All products are above minimum stock levels.",
      statusLabel: "Status: Low Stock Warning",
      supplierLabel: "Supplier",
    },
  },
  addProduct: {
    title: "Add New Product",
    success: "Product successfully added! Status set to 'Pending Approval'.",
    form: {
      name: "Product Name",
      category: "Product Category",
      brand: "Brand Name",
      supplier: "Supplier Name",
      purchasePrice: "Purchase Price (₹)",
      sellingPrice: "Selling Price (₹)",
      quantity: "Product Quantity",
      unitType: "Unit Type",
      location: "Storage Location",
      description: "Product Description",
      image: "Product Image",
      optional: "(Optional)",
    },
    placeholders: {
      name: "e.g. Wireless Mouse",
      category: "Select Category...",
      brand: "e.g. Logitech",
      supplier: "Select Supplier...",
      price: "0.00",
      quantity: "e.g. 100",
      location: "Select Location...",
      description: "Detailed product description...",
    },
    buttons: {
      add: "Add Product",
      reset: "Reset Form",
    },
  },
  movementTracker: {
    title: "Record Product Movement",
    subtitle: "Scan or search for a product to log physical movement, damages, or restocks.",
    searchLabel: "Search Product (Name or SKU)",
    searchPlaceholder: "e.g. Wireless Mouse",
    searchButton: "Search",
    clearButton: "CLEAR",
    noProducts: "No products found for",
    emptyState: "Search and select a product to begin recording movements.",
    currentStock: "Current Stock",
    location: "Location",
    unassigned: "Unassigned",
    quantityLabel: "Quantity",
    reasonLabel: "Reason/Action",
    infoText: "Based on the reason selected, stock will automatically increase (Restock, Return) or decrease (Damage, Sent Out).",
    fromLocation: "From Location",
    toLocation: "To Location",
    optional: "Optional",
    confirmButton: "Confirm Movement",
    recording: "Recording...",
    success: "Successfully recorded movement! New stock level:",
    errorUpdate: "Failed to record movement. Check stock levels.",
  },
  barcodeScanner: {
    title: "Live Barcode Scanner",
    subtitle: "Use your device camera to scan a product barcode (SKU) and view live inventory details.",
    manualEntry: "OR ENTER MANUALLY",
    manualPlaceholder: "Enter Barcode / SKU",
    searchButton: "Search",
    searching: "Searching inventory...",
    scanFailed: "Scan Failed",
    noProduct: "No product found in inventory with barcode:",
    units: "Units",
    recordMovement: "Record Movement for this Product",
    scanAnother: "Scan Another Item",
    table: {
      sku: "SKU / Barcode",
      category: "Category",
      stock: "Current Stock",
      location: "Location",
      price: "Price",
      supplier: "Supplier",
    },
  },
  profile: {
    title: "My Profile",
    subtitle: "View and update your personal information.",
    fullName: "Full Name",
    phone: "Phone Number",
    address: "Address",
    city: "City",
    state: "State",
    pincode: "Pincode",
    shiftTime: "Shift Time",
    profilePhoto: "Profile Photo URL (Optional)",
    changePassword: "Change Password",
    passwordPlaceholder: "Leave blank to keep current",
    accountDetails: "Account Details (Read-Only)",
    email: "Email Address",
    role: "Role",
    shop: "Assigned Shop",
    updateButton: "Update Profile",
    updating: "Updating...",
    noShift: "-- No Shift Assigned --",
    success: "Profile updated successfully!",
    errorLoad: "Failed to load profile data.",
    errorUpdate: "Failed to update profile.",
    managerDetails: "Additional Manager Details",
    managerId: "Manager ID",
    department: "Department",
    joiningDate: "Joining Date",
    changePasswordButton: "Change Password",
  },
  changePassword: {
    title: "Change Password",
    subtitle: "Ensure your account is secure by using a strong password.",
    oldPassword: "Old Password",
    newPassword: "New Password",
    confirmPassword: "Confirm New Password",
    submitButton: "Update Password",
    success: "Password changed successfully",
    placeholders: {
      old: "Enter old password",
      new: "Enter new password",
      confirm: "Confirm new password",
    },
    validation: {
      required: "All fields are required",
      mismatch: "Passwords do not match",
      strength: "Password must be at least 8 characters, include uppercase, lowercase and a special character",
    }
  },
  productList: {
    title: "View Product List",
    searchPlaceholder: "Search by name or SKU...",
    table: {
      img: "Img",
      sku: "SKU",
      name: "Product Name",
      category: "Category",
      brand: "Brand",
      qty: "Qty",
      price: "Sell Price",
      status: "Status",
      actions: "Actions",
    },
    editModal: {
      title: "Edit Product",
      name: "Product Name",
      category: "Category",
      brand: "Brand",
      qty: "Quantity",
      price: "Price",
    },
    noProducts: "No products found.",
  },
  productManagement: {
    stats: {
      total: "Total Products",
      lowStock: "Low Stock",
      outOfStock: "Out of Stock",
      value: "Inventory Value",
    },
    searchPlaceholder: "Search by name or SKU...",
    categoriesLabel: "Categories",
    allCategories: "All Categories",
    table: {
      img: "Img",
      sku: "SKU",
      name: "Product Name",
      category: "Category",
      brand: "Brand",
      supplier: "Supplier",
      buyPrice: "Buy Price",
      sellPrice: "Sell Price",
      qty: "Quantity",
      status: "Status",
      actions: "Actions",
    },
    badges: {
      outOfStock: "Out of Stock",
      lowStock: "Low Stock",
      inStock: "In Stock",
    },
    modals: {
      edit: {
        title: "Edit Product",
        name: "Name",
        brand: "Brand",
        category: "Category",
        qty: "Quantity",
        buyPrice: "Buy Price",
        sellPrice: "Sell Price",
      },
      stock: {
        title: "Update Stock",
        product: "Product",
        label: "Add/Subtract Quantity",
        placeholder: "e.g. 10 or -5",
        update: "Update",
      },
      delete: {
        title: "Delete Product?",
        confirmLabel: "Are you sure you want to delete",
        warning: "This action cannot be undone.",
        confirmButton: "Delete",
      },
      buttons: {
        save: "Save Changes",
        cancel: "Cancel",
      },
    },
    pagination: {
      page: "Page",
      of: "of",
      prev: "Previous",
      next: "Next",
    },
  },
};

export default textData;
